# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
#   sqlc-gen-better-python v0.4.4
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "delete_old_mlb_bets",
    "delete_old_nba_bets",
    "delete_old_nfl_bets",
    "delete_old_wnba_bets",
)

import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime

    import asyncpg
    import asyncpg.cursor

    QueryResultsArgsType: typing.TypeAlias = (
        int
        | float
        | str
        | memoryview
        | datetime.date
        | datetime.time
        | datetime.datetime
        | datetime.timedelta
        | None
    )

    ConnectionLike: typing.TypeAlias = (
        asyncpg.Connection[asyncpg.Record]
        | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]
    )


DELETE_OLD_MLB_BETS: typing.Final[str] = """-- name: DeleteOldMlbBets :exec
DELETE FROM v2_mlb_daily_bets WHERE created_at < NOW() - INTERVAL '1 week'
"""

DELETE_OLD_NBA_BETS: typing.Final[str] = """-- name: DeleteOldNbaBets :exec
DELETE FROM v2_nba_daily_bets WHERE created_at < NOW() - INTERVAL '1 week' RETURNING id, analysis, created_at, price, game_time, game_tag
"""

DELETE_OLD_NFL_BETS: typing.Final[str] = """-- name: DeleteOldNflBets :exec
DELETE FROM v2_nfl_daily_bets WHERE created_at < NOW() - INTERVAL '1 week'
"""

DELETE_OLD_WNBA_BETS: typing.Final[str] = """-- name: DeleteOldWnbaBets :exec
DELETE FROM v2_wnba_daily_bets WHERE created_at < NOW() - INTERVAL '1 week'
"""


async def delete_old_mlb_bets(conn: ConnectionLike) -> None:
    await conn.execute(DELETE_OLD_MLB_BETS)


async def delete_old_nba_bets(conn: ConnectionLike) -> None:
    await conn.execute(DELETE_OLD_NBA_BETS)


async def delete_old_nfl_bets(conn: ConnectionLike) -> None:
    await conn.execute(DELETE_OLD_NFL_BETS)


async def delete_old_wnba_bets(conn: ConnectionLike) -> None:
    await conn.execute(DELETE_OLD_WNBA_BETS)
