# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.4
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "MlbCopyAnalysisParams",
    "MlbRecentAnalysisKeysRow",
    "QueryResults",
    "mlb_analysis_exists",
    "mlb_copy_analysis",
    "mlb_dedupe_recent_analysis",
    "mlb_players",
    "mlb_recent_analysis_keys",
    "mlb_teams",
    "mlb_upsert_analysis",
)

import datetime
import decimal
import msgspec
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | decimal.Decimal | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from daily_bets.db import models


class MlbCopyAnalysisParams(msgspec.Struct):
    analysis: str
    price: float
    game_time: datetime.datetime
    game_tag: str


class MlbRecentAnalysisKeysRow(msgspec.Struct):
    game_time: datetime.datetime
    game_tag: str
    player_id: int
    stat: typing.Any | None
    line: decimal.Decimal


MLB_ANALYSIS_EXISTS: typing.Final[str] = """-- name: MlbAnalysisExists :one
SELECT EXISTS (
    SELECT 1
    FROM public.v2_mlb_daily_bets
    WHERE
        game_time = $1
        AND game_tag = $2
        AND (analysis->'input'->>'player_id')::int = $3
        AND analysis->'input'->>'stat' = $4
        AND (analysis->'input'->>'line')::numeric = $5::numeric
)
"""

MLB_COPY_ANALYSIS: typing.Final[str] = """-- name: MlbCopyAnalysis :copyfrom
INSERT INTO v2_mlb_daily_bets (analysis, price, game_time, game_tag) VALUES ($1, $2, $3, $4)
"""

MLB_DEDUPE_RECENT_ANALYSIS: typing.Final[str] = """-- name: MlbDedupeRecentAnalysis :execrows
WITH ranked AS (
    SELECT
        id,
        row_number() OVER (
            PARTITION BY
                game_time,
                game_tag,
                (analysis->'input'->>'player_id')::int,
                analysis->'input'->>'stat',
                (analysis->'input'->>'line')::numeric
            ORDER BY created_at DESC, id DESC
        ) AS rn
    FROM public.v2_mlb_daily_bets
    WHERE created_at >= now() - make_interval(days => $1)
)
DELETE FROM public.v2_mlb_daily_bets b
USING ranked r
WHERE b.id = r.id AND r.rn > 1
"""

MLB_PLAYERS: typing.Final[str] = """-- name: MlbPlayers :many
SELECT id, player_id, long_name, team_abv, pos, height, weight, bat, throw, b_day, mlb_headshot, espn_headshot, espn_status, injury_description, injury_return FROM mlb_players
"""

MLB_RECENT_ANALYSIS_KEYS: typing.Final[str] = """-- name: MlbRecentAnalysisKeys :many
SELECT
    game_time,
    game_tag,
    (analysis->'input'->>'player_id')::int AS player_id,
    analysis->'input'->>'stat' AS stat,
    (analysis->'input'->>'line')::numeric AS line
FROM public.v2_mlb_daily_bets
WHERE created_at >= now() - make_interval(days => $1)
"""

MLB_TEAMS: typing.Final[str] = """-- name: MlbTeams :many
SELECT team_abv, team_city, team_name, conference, division, rs, ra, wins, losses, run_diff FROM mlb_teams
"""

MLB_UPSERT_ANALYSIS: typing.Final[str] = """-- name: MlbUpsertAnalysis :one
WITH inserted AS (
    INSERT INTO public.v2_mlb_daily_bets (analysis, price, game_time, game_tag)
    SELECT $1, $2, $3, $4
    WHERE NOT EXISTS (
        SELECT 1
        FROM public.v2_mlb_daily_bets
        WHERE
            game_time = $3
            AND game_tag = $4
            AND (analysis->'input'->>'player_id')::int =
                ($1::json->'input'->>'player_id')::int
            AND analysis->'input'->>'stat' = ($1::json->'input'->>'stat')
            AND (analysis->'input'->>'line')::numeric =
                ($1::json->'input'->>'line')::numeric
    )
    RETURNING 1
)
SELECT count(*) FROM inserted
"""


T = typing.TypeVar("T")


class QueryResults(typing.Generic[T]):
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]
        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def mlb_analysis_exists(conn: ConnectionLike, *, game_time: datetime.datetime, game_tag: str, analysis: str, analysis: str, dollar_5: decimal.Decimal) -> bool | None:
    row = await conn.fetchrow(MLB_ANALYSIS_EXISTS, game_time, game_tag, analysis, analysis, dollar_5)
    if row is None:
        return None
    return row[0]


async def mlb_copy_analysis(conn: ConnectionLike, *, params: collections.abc.Sequence[MlbCopyAnalysisParams]) -> int:
    records = [
        (param.analysis, param.price, param.game_time, param.game_tag)
        for param in params
    ]
    r = await conn.copy_records_to_table("v2_mlb_daily_bets", columns=["analysis", "price", "game_time", "game_tag"], records=records)
    return int(n) if (p := r.split()) and (n := p[-1]).isdigit() else 0


async def mlb_dedupe_recent_analysis(conn: ConnectionLike, *, days: int) -> int:
    r = await conn.execute(MLB_DEDUPE_RECENT_ANALYSIS, days)
    return int(n) if (p := r.split()) and (n := p[-1]).isdigit() else 0


def mlb_players(conn: ConnectionLike) -> QueryResults[models.MlbPlayer]:
    def _decode_hook(row: asyncpg.Record) -> models.MlbPlayer:
        return models.MlbPlayer(id=row[0], player_id=row[1], long_name=row[2], team_abv=row[3], pos=row[4], height=row[5], weight=row[6], bat=row[7], throw=row[8], b_day=row[9], mlb_headshot=row[10], espn_headshot=row[11], espn_status=row[12], injury_description=row[13], injury_return=row[14])
    return QueryResults[models.MlbPlayer](conn, MLB_PLAYERS, _decode_hook)


def mlb_recent_analysis_keys(conn: ConnectionLike, *, days: int) -> QueryResults[MlbRecentAnalysisKeysRow]:
    def _decode_hook(row: asyncpg.Record) -> MlbRecentAnalysisKeysRow:
        return MlbRecentAnalysisKeysRow(game_time=row[0], game_tag=row[1], player_id=row[2], stat=row[3], line=row[4])
    return QueryResults[MlbRecentAnalysisKeysRow](conn, MLB_RECENT_ANALYSIS_KEYS, _decode_hook, days)


def mlb_teams(conn: ConnectionLike) -> QueryResults[models.MlbTeam]:
    def _decode_hook(row: asyncpg.Record) -> models.MlbTeam:
        return models.MlbTeam(team_abv=row[0], team_city=row[1], team_name=row[2], conference=row[3], division=row[4], rs=row[5], ra=row[6], wins=row[7], losses=row[8], run_diff=row[9])
    return QueryResults[models.MlbTeam](conn, MLB_TEAMS, _decode_hook)


async def mlb_upsert_analysis(conn: ConnectionLike, *, analysis: str, price: float, game_time: datetime.datetime, game_tag: str) -> int | None:
    row = await conn.fetchrow(MLB_UPSERT_ANALYSIS, analysis, price, game_time, game_tag)
    if row is None:
        return None
    return row[0]
