# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.5
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "BracketiqAtsHistorical",
    "BracketiqFanmatchHistorical",
    "BracketiqKenpomFourfactor",
    "BracketiqKenpomHeight",
    "BracketiqKenpomRating",
    "BracketiqKenpomTeamstatsDef",
    "BracketiqKenpomTeamstatsOff",
    "BracketiqOddsHistorical",
    "BracketiqSlateToday",
    "CbbGamePrediction",
    "MlbPlayer",
    "MlbPlayerGameStat",
    "MlbProbablePitcher",
    "MlbTeam",
    "NbaArena",
    "NbaBacktestingResult",
    "NbaCoach",
    "NbaDailyBet",
    "NbaGamePrediction",
    "NbaGameResult",
    "NbaHistoricalOdd",
    "NbaMlFeatureSnapshot",
    "NbaPlayer",
    "NbaPlayerGameStat",
    "NbaPlayerSeasonStat",
    "NbaSeason",
    "NbaTeam",
    "NbaTeamDefenseByPosition",
    "NbaTeamRating",
    "NflDailyBet",
    "PlayerSeasonVorp",
    "PropgptMlbBetResult",
    "PropgptMlbBullpenAppearance",
    "PropgptMlbFactorWeight",
    "PropgptMlbGame",
    "PropgptMlbModelPerformanceDaily",
    "PropgptMlbOddsSnapshot",
    "PropgptMlbOutcome",
    "PropgptMlbPark",
    "PropgptMlbParkFactor",
    "PropgptMlbPitcherGameLog",
    "PropgptMlbPlayer",
    "PropgptMlbPrediction",
    "PropgptMlbSchemaMigration",
    "PropgptMlbTeam",
    "PropgptMlbTeamGameLog",
    "PropgptMlbWeatherObservation",
    "V2MlbDailyBet",
    "V2NbaAltDailyBet",
    "V2NbaDailyBet",
    "V2NbaDailyBetsBackup",
    "V2NflDailyBet",
    "V2NflDailyBetsBackup",
    "V2WnbaDailyBet",
    "V3NflGame",
    "V3NflGameStat",
    "V3NflPlayer",
    "V3NflTeam",
    "V3NflTeams2024Stat",
    "WnbaPlayer",
    "WnbaPlayerGameStat",
    "WnbaPlayerSeasonStat",
    "WnbaSeason",
    "WnbaTeam",
)

import msgspec
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime
    import decimal


class BracketiqAtsHistorical(msgspec.Struct):
    game_date: str | None
    home_team: str | None
    away_team: str | None
    kenpom_predicted_margin: float | None
    vegas_spread: float | None
    actual_margin_home: float | None
    covered_vegas: bool | None
    covered_kenpom: bool | None
    kenpom_vs_vegas_edge: float | None
    vegas_total: float | None
    actual_total: float | None
    over_under_result: str | None
    updated_at: datetime.datetime | None


class BracketiqFanmatchHistorical(msgspec.Struct):
    fanmatch_date: str | None
    game: str | None
    predicted_winner: str | None
    predicted_loser: str | None
    predicted_mov: float | None
    predicted_score: str | None
    winner: str | None
    loser: str | None
    winner_score: str | None
    loser_score: str | None
    actual_mov: float | None
    location: str | None
    thrill_score: str | None
    updated_at: datetime.datetime | None


class BracketiqKenpomFourfactor(msgspec.Struct):
    team: str | None
    conference: str | None
    adjtempo: str | None
    adjoe: str | None
    off_efg_pct: str | None
    off_to_pct: str | None
    off_or_pct: str | None
    off_ftrate: str | None
    adjde: str | None
    def_efg_pct: str | None
    def_to_pct: str | None
    def_or_pct: str | None
    def_ftrate: str | None
    updated_at: datetime.datetime | None


class BracketiqKenpomHeight(msgspec.Struct):
    team: str | None
    conference: str | None
    avghgt: str | None
    effhgt: str | None
    c_hgt: str | None
    pf_hgt: str | None
    sf_hgt: str | None
    sg_hgt: str | None
    pg_hgt: str | None
    experience: str | None
    bench: str | None
    continuity: str | None
    updated_at: datetime.datetime | None


class BracketiqKenpomRating(msgspec.Struct):
    team: str | None
    conference: str | None
    rank: str | None
    adj_oe: str | None
    adj_de: str | None
    adj_em: str | None
    adj_tempo: str | None
    luck: str | None
    updated_at: datetime.datetime | None


class BracketiqKenpomTeamstatsDef(msgspec.Struct):
    team: str | None
    conference: str | None
    three_p_pct: str | None
    two_p_pct: str | None
    ft_pct: str | None
    blk_pct: str | None
    stl_pct: str | None
    nst_pct: str | None
    a_pct: str | None
    three_pa_pct: str | None
    adjde: str | None
    updated_at: datetime.datetime | None


class BracketiqKenpomTeamstatsOff(msgspec.Struct):
    team: str | None
    conference: str | None
    three_p_pct: str | None
    two_p_pct: str | None
    ft_pct: str | None
    blk_pct: str | None
    stl_pct: str | None
    nst_pct: str | None
    a_pct: str | None
    three_pa_pct: str | None
    adjoe: str | None
    updated_at: datetime.datetime | None


class BracketiqOddsHistorical(msgspec.Struct):
    game_date: str | None
    home_team: str | None
    away_team: str | None
    home_team_kenpom: str | None
    away_team_kenpom: str | None
    consensus_spread: float | None
    consensus_total: float | None
    num_bookmakers: int | None
    updated_at: datetime.datetime | None


class BracketiqSlateToday(msgspec.Struct):
    away_team: str | None
    home_team: str | None
    away_team_odds_api: str | None
    home_team_odds_api: str | None
    away_team_kenpom: str | None
    home_team_kenpom: str | None
    vegas_spread_home_pov: float | None
    vegas_total: float | None
    vegas_implied_prob_home: float | None
    vegas_implied_prob_away: float | None
    recency_adjustment_pts: float | None
    spread_source: str | None
    ou_source: str | None
    kenpom_predicted_margin_home_pov: float | None
    kenpom_predicted_total: float | None
    kenpom_predicted_score_home: str | None
    kenpom_predicted_score_away: str | None
    model_win_prob_home: float | None
    kenpom_win_prob_home: float | None
    spread_edge: float | None
    spread_edge_confidence: str | None
    historical_cover_rate: str | None
    moneyline_edge: float | None
    moneyline_conviction: str | None
    over_under_edge: float | None
    over_under_conviction: str | None
    spread_edge_interpretation: str | None
    moneyline_edge_interpretation: str | None
    ou_edge_interpretation: str | None
    slow_underdog_flag: bool | None
    slow_underdog_note: str | None
    markets: str | None
    kenpom_fanmatch_margin_home_pov: str | None
    kenpom_fanmatch_total: str | None
    sanity_adjacent: str | None
    sanity_note: str | None
    updated_at: datetime.datetime | None


class CbbGamePrediction(msgspec.Struct):
    id: int
    game_id: str
    prediction_date: datetime.date
    snapshot_date: str | None
    home_team: str
    away_team: str
    predicted_winner: str | None
    predicted_spread: decimal.Decimal | None
    vegas_spread: decimal.Decimal | None
    vegas_total: decimal.Decimal | None
    vegas_implied_prob_home: decimal.Decimal | None
    vegas_implied_prob_away: decimal.Decimal | None
    home_win_prob: decimal.Decimal | None
    away_win_prob: decimal.Decimal | None
    confidence: str | None
    home_adj_em: decimal.Decimal | None
    away_adj_em: decimal.Decimal | None
    home_offensive_em: decimal.Decimal | None
    home_defensive_em: decimal.Decimal | None
    away_offensive_em: decimal.Decimal | None
    away_defensive_em: decimal.Decimal | None
    matchup_pace: decimal.Decimal | None
    short_answer: str | None
    long_answer: str | None
    head_to_head: str | None
    schema_version: str | None
    model_version: str | None
    source_generated_at: datetime.datetime | None
    source_updated_at: datetime.datetime | None
    markets: str
    factors: str
    insights: str
    head_to_head_games: str
    home_last_10_games: str
    away_last_10_games: str
    home_context: str
    away_context: str
    game_payload: str
    source_payload: str
    source_endpoint: str
    github_run_id: str | None
    ingested_at: datetime.datetime
    updated_at: datetime.datetime


class MlbPlayer(msgspec.Struct):
    id: int
    player_id: int
    long_name: str
    team_abv: str
    pos: str
    height: str
    weight: int
    bat: str | None
    throw: str | None
    b_day: datetime.date | None
    mlb_headshot: str | None
    espn_headshot: str | None
    espn_status: str | None
    injury_description: str | None
    injury_return: str | None


class MlbPlayerGameStat(msgspec.Struct):
    player_id: int
    game_id: str
    team: str | None
    started: bool | None
    starting_position: str | None
    all_positions_played: str | None
    bb: int | None
    ab: int | None
    h: int | None
    hr: int | None
    rbi: int | None
    so: int | None
    avg: float | None
    tb: int | None
    doubles: int | None
    triples: int | None
    r: int | None
    ibb: int | None
    sf: int | None
    sac: int | None
    hbp: int | None
    gidp: int | None
    p_bb: int | None
    p_h: int | None
    p_hr: int | None
    p_er: int | None
    p_so: int | None
    win: str | None
    loss: str | None
    save: str | None
    era: float | None
    innings_pitched: float | None
    fielding_e: int | None
    passed_ball: int | None
    of_assists: int | None
    pickoffs: int | None
    sb: int | None
    cs: int | None
    po: int | None


class MlbProbablePitcher(msgspec.Struct):
    date_scraped: datetime.date
    player_id: int | None
    name: str
    team_abv: str | None
    career_vs_opp_pa: int | None
    career_vs_opp_kpct: float | None
    career_vs_opp_bbpct: float | None
    career_vs_opp_avg: float | None
    career_vs_opp_woba: float | None
    exit_velo: float | None
    launch_angle: float | None
    xba: float | None
    xslg: float | None
    xwoba: float | None
    probable_pitcher_score: float
    probable_pitcher_grade: str
    scraped_at: datetime.datetime | None


class MlbTeam(msgspec.Struct):
    team_abv: str
    team_city: str | None
    team_name: str
    conference: str
    division: str
    rs: int
    ra: int
    wins: int
    losses: int
    run_diff: int


class NbaArena(msgspec.Struct):
    id: int
    team: str
    arena_name: str | None
    city: str | None
    state: str | None
    latitude: decimal.Decimal | None
    longitude: decimal.Decimal | None
    altitude_ft: int | None
    timezone: str | None


class NbaBacktestingResult(msgspec.Struct):
    id: int
    bet_id: int | None
    player_id: int | None
    stat_type: str | None
    line: decimal.Decimal | None
    recommendation: str | None
    grade: int | None
    game_date: datetime.date | None
    actual_value: decimal.Decimal | None
    hit: bool | None
    created_at: datetime.datetime | None


class NbaCoach(msgspec.Struct):
    id: int
    team: str
    coach_name: str
    tenure_years: int | None
    championships: int | None
    tier: str | None
    close_game_pct: decimal.Decimal | None
    consistency_score: decimal.Decimal | None
    season: str | None
    updated_at: datetime.datetime | None


class NbaDailyBet(msgspec.Struct):
    id: int
    player_id: str
    team_id: str
    opponent_id: str
    stat_type: str
    line: float
    bet_grade: str
    created_at: datetime.datetime


class NbaGamePrediction(msgspec.Struct):
    id: int
    prediction_date: datetime.date
    home_team: str
    away_team: str
    predicted_winner: str | None
    predicted_spread: decimal.Decimal | None
    home_win_prob: decimal.Decimal | None
    away_win_prob: decimal.Decimal | None
    confidence: str | None
    home_adj_em: decimal.Decimal | None
    away_adj_em: decimal.Decimal | None
    matchup_pace: decimal.Decimal | None
    short_answer: str | None
    long_answer: str | None
    head_to_head: str | None
    factors: str
    home_context: str
    away_context: str
    game_payload: str
    source_payload: str
    source_endpoint: str
    github_run_id: str | None
    ingested_at: datetime.datetime
    updated_at: datetime.datetime
    home_offensive_em: decimal.Decimal | None
    home_defensive_em: decimal.Decimal | None
    away_offensive_em: decimal.Decimal | None
    away_defensive_em: decimal.Decimal | None
    head_to_head_games: str
    home_last_10_games: str
    away_last_10_games: str
    vegas_spread: decimal.Decimal | None
    vegas_home_moneyline: int | None
    vegas_away_moneyline: int | None


class NbaGameResult(msgspec.Struct):
    id: int
    game_id: str
    game_date: datetime.date
    home_team: str
    away_team: str
    home_score: int | None
    away_score: int | None
    margin: int | None
    season: str | None
    status: str | None
    created_at: datetime.datetime | None
    updated_at: datetime.datetime | None


class NbaHistoricalOdd(msgspec.Struct):
    id: int
    game_id: str | None
    game_date: datetime.date
    home_team: str
    away_team: str
    spread: decimal.Decimal | None
    home_moneyline: int | None
    away_moneyline: int | None
    total: decimal.Decimal | None
    source: str | None
    season: str | None
    captured_at: datetime.datetime | None


class NbaMlFeatureSnapshot(msgspec.Struct):
    id: int
    player_id: int | None
    game_date: datetime.date | None
    stat_type: str | None
    avg_5: decimal.Decimal | None
    avg_10: decimal.Decimal | None
    avg_20: decimal.Decimal | None
    std_10: decimal.Decimal | None
    minutes_avg_10: decimal.Decimal | None
    opp_def_rtg: decimal.Decimal | None
    opp_pace: decimal.Decimal | None
    is_home: bool | None
    days_rest: int | None
    season_avg: decimal.Decimal | None
    games_played: int | None
    created_at: datetime.datetime | None


class NbaPlayer(msgspec.Struct):
    id: int
    name: str
    position: str | None
    team_id: int
    player_pic: str | None
    player_id: int
    injury: str | None


class NbaPlayerGameStat(msgspec.Struct):
    id: int
    player_id: int
    game_id: str
    team_id: int
    minutes_played: decimal.Decimal | None
    points: int | None
    rebounds: int | None
    assists: int | None
    steals: int | None
    blocks: int | None
    turnovers: int | None
    offensive_rebounds: int | None
    defensive_rebounds: int | None
    free_throw_percentage: decimal.Decimal | None
    plus_minus: decimal.Decimal | None
    technical_fouls: int | None
    field_goal_attempts: int | None
    three_point_fg_percentage: decimal.Decimal | None
    field_goals_made: int | None
    field_goal_percentage: decimal.Decimal | None
    three_point_fg_made: int | None
    free_throw_attempts: int | None
    three_point_fg_attempts: int | None
    personal_fouls: int | None
    free_throws_made: int | None
    fantasy_points: decimal.Decimal | None
    home_away: str | None
    opponent: str | None
    game_date: datetime.date | None
    team_abv: str | None


class NbaPlayerSeasonStat(msgspec.Struct):
    id: int
    player_id: int | None
    season_id: int | None
    games_played: int | None
    points_per_game: decimal.Decimal | None
    rebounds_per_game: decimal.Decimal | None
    assists_per_game: decimal.Decimal | None
    steals_per_game: decimal.Decimal | None
    blocks_per_game: decimal.Decimal | None
    turnovers_per_game: decimal.Decimal | None
    field_goal_percentage: decimal.Decimal | None
    three_point_percentage: decimal.Decimal | None
    free_throw_percentage: decimal.Decimal | None
    minutes_per_game: decimal.Decimal | None
    offensive_rebounds_per_game: decimal.Decimal | None
    defensive_rebounds_per_game: decimal.Decimal | None
    field_goals_made_per_game: decimal.Decimal | None
    field_goals_attempted_per_game: decimal.Decimal | None
    three_pointers_made_per_game: decimal.Decimal | None
    three_pointers_attempted_per_game: decimal.Decimal | None
    free_throws_made_per_game: decimal.Decimal | None
    free_throws_attempted_per_game: decimal.Decimal | None


class NbaSeason(msgspec.Struct):
    id: int
    season_year: str


class NbaTeam(msgspec.Struct):
    id: int
    name: str
    team_city: str
    team_abv: str
    conference: str
    ppg: float | None
    oppg: float | None
    wins: int | None
    loss: int | None
    division: str | None
    team_bpg: float | None
    team_spg: float | None
    team_apg: float | None
    team_fga: float | None
    team_fgm: float | None
    team_fta: float | None
    team_tov: float | None
    pace: float | None
    def_rtg: float | None


class NbaTeamDefenseByPosition(msgspec.Struct):
    id: int
    team_abv: str | None
    season: str | None
    vs_position: str | None
    pts_allowed_per_game: decimal.Decimal | None
    reb_allowed_per_game: decimal.Decimal | None
    ast_allowed_per_game: decimal.Decimal | None
    games_sample_size: int | None
    updated_at: datetime.datetime | None


class NbaTeamRating(msgspec.Struct):
    id: int
    team: str
    season: str
    adj_em: decimal.Decimal | None
    adj_off: decimal.Decimal | None
    adj_def: decimal.Decimal | None
    games: int | None
    last_game_date: datetime.date | None
    calculated_at: datetime.datetime | None


class NflDailyBet(msgspec.Struct):
    id: int
    player_id: str
    team_code: str
    stat: str
    line: decimal.Decimal
    opponent: str
    bet_grade: str
    created_at: datetime.datetime | None
    price: float | None


class PlayerSeasonVorp(msgspec.Struct):
    id: int
    player_id: str | None
    player_name: str | None
    team: str | None
    season: str | None
    games_played: int | None
    total_minutes: decimal.Decimal | None
    pct_minutes: decimal.Decimal | None
    team_games: int | None
    estimated_bpm: decimal.Decimal | None
    vorp: decimal.Decimal | None
    model_version: str | None
    calculated_at: datetime.datetime | None


class PropgptMlbBetResult(msgspec.Struct):
    id: int
    prediction_id: int
    game_id: int
    bet_type: str
    side: str
    line_taken: decimal.Decimal | None
    odds_taken: int
    stake: decimal.Decimal
    result: str | None
    pnl: decimal.Decimal | None
    closing_line_total: decimal.Decimal | None
    closing_line_ml: int | None
    clv_pct: decimal.Decimal | None
    settled_at: datetime.datetime | None


class PropgptMlbBullpenAppearance(msgspec.Struct):
    player_id: int
    game_id: int
    team_id: int
    ip: decimal.Decimal | None
    pitches: int | None
    er: int | None
    leverage_index: decimal.Decimal | None
    inherited_runners: int | None
    days_rest_before: int | None


class PropgptMlbFactorWeight(msgspec.Struct):
    id: int
    as_of_date: datetime.date
    factor_name: str
    alpha: decimal.Decimal
    beta: decimal.Decimal
    reliability: decimal.Decimal | None
    recent_brier: decimal.Decimal | None
    recent_log_loss: decimal.Decimal | None
    sample_size: int | None


class PropgptMlbGame(msgspec.Struct):
    game_id: int
    game_date: datetime.date
    season: int
    home_team_id: int
    away_team_id: int
    park_id: int | None
    game_time_utc: datetime.datetime | None
    home_sp_id: int | None
    away_sp_id: int | None
    status: str | None
    is_doubleheader: bool | None
    doubleheader_game_num: int | None
    created_at: datetime.datetime
    updated_at: datetime.datetime


class PropgptMlbModelPerformanceDaily(msgspec.Struct):
    as_of_date: datetime.date
    model_version: str
    games_predicted: int
    total_rmse: decimal.Decimal | None
    total_mae: decimal.Decimal | None
    over_under_hits: int | None
    over_under_pushes: int | None
    over_under_total: int | None
    ml_brier: decimal.Decimal | None
    ml_log_loss: decimal.Decimal | None
    ml_correct: int | None
    recommended_bets: int | None
    bets_won: int | None
    bets_lost: int | None
    bets_pushed: int | None
    daily_pnl: decimal.Decimal | None
    daily_roi_pct: decimal.Decimal | None


class PropgptMlbOddsSnapshot(msgspec.Struct):
    id: int
    game_id: int
    book: str
    snapshot_time: datetime.datetime
    is_closing: bool
    total_line: decimal.Decimal | None
    over_odds: int | None
    under_odds: int | None
    ml_home: int | None
    ml_away: int | None
    rl_home_spread: decimal.Decimal | None
    rl_home_odds: int | None
    rl_away_odds: int | None


class PropgptMlbOutcome(msgspec.Struct):
    game_id: int
    home_score: int
    away_score: int
    total_runs: int | None
    home_won: bool | None
    extra_innings: bool | None
    final_innings: decimal.Decimal | None
    recorded_at: datetime.datetime


class PropgptMlbPark(msgspec.Struct):
    park_id: int
    name: str
    team_id: int | None
    is_dome: bool
    has_retractable_roof: bool
    orientation_deg: decimal.Decimal | None
    altitude_ft: int | None
    latitude: decimal.Decimal | None
    longitude: decimal.Decimal | None
    lf_dist_ft: int | None
    cf_dist_ft: int | None
    rf_dist_ft: int | None
    timezone: str | None


class PropgptMlbParkFactor(msgspec.Struct):
    park_id: int
    season: int
    runs_factor: decimal.Decimal | None
    hr_factor: decimal.Decimal | None
    hr_factor_lhb: decimal.Decimal | None
    hr_factor_rhb: decimal.Decimal | None
    doubles_factor: decimal.Decimal | None
    triples_factor: decimal.Decimal | None


class PropgptMlbPitcherGameLog(msgspec.Struct):
    player_id: int
    game_id: int
    team_id: int
    is_starter: bool
    ip: decimal.Decimal | None
    batters_faced: int | None
    pitches: int | None
    strikes: int | None
    h: int | None
    r: int | None
    er: int | None
    bb: int | None
    k: int | None
    hr: int | None
    hbp: int | None
    ground_balls: int | None
    fly_balls: int | None
    line_drives: int | None


class PropgptMlbPlayer(msgspec.Struct):
    player_id: int
    full_name: str
    primary_position: str | None
    throws: str | None
    bats: str | None
    birth_date: datetime.date | None
    mlb_debut_date: datetime.date | None


class PropgptMlbPrediction(msgspec.Struct):
    id: int
    game_id: int
    model_version: str
    made_at: datetime.datetime
    predicted_total: decimal.Decimal | None
    p_over: decimal.Decimal | None
    p_home_win: decimal.Decimal | None
    line_at_prediction_total: decimal.Decimal | None
    line_at_prediction_over_odds: int | None
    line_at_prediction_under_odds: int | None
    line_at_prediction_ml_home: int | None
    line_at_prediction_ml_away: int | None
    features_json: str
    total_pick: str | None
    total_grade: str | None
    total_edge_pct: decimal.Decimal | None
    ml_pick: str | None
    ml_grade: str | None
    ml_edge_pct: decimal.Decimal | None
    explanation: str | None
    explanation_top_factors: str | None


class PropgptMlbSchemaMigration(msgspec.Struct):
    version: str
    applied_at: datetime.datetime


class PropgptMlbTeam(msgspec.Struct):
    team_id: int
    abbr: str
    name: str
    league: str
    division: str
    primary_park_id: int | None


class PropgptMlbTeamGameLog(msgspec.Struct):
    team_id: int
    game_id: int
    is_home: bool
    opp_starter_throws: str | None
    runs_scored: int | None
    runs_allowed: int | None
    hits: int | None
    doubles: int | None
    triples: int | None
    hr: int | None
    bb: int | None
    k: int | None
    hbp: int | None
    sb: int | None
    cs: int | None
    lob: int | None


class PropgptMlbWeatherObservation(msgspec.Struct):
    game_id: int
    observed_for_time: datetime.datetime | None
    pulled_at: datetime.datetime
    source: str
    temp_f: decimal.Decimal | None
    feels_like_f: decimal.Decimal | None
    wind_mph: decimal.Decimal | None
    wind_dir_deg: decimal.Decimal | None
    precip_pct: decimal.Decimal | None
    humidity_pct: decimal.Decimal | None
    cloud_cover_pct: decimal.Decimal | None
    is_dome_game: bool


class V2MlbDailyBet(msgspec.Struct):
    id: int
    analysis: str
    created_at: datetime.datetime
    price: float
    game_time: datetime.datetime
    game_tag: str


class V2NbaAltDailyBet(msgspec.Struct):
    id: int
    analysis: str
    created_at: datetime.datetime
    price: float | None
    game_time: datetime.datetime
    game_tag: str


class V2NbaDailyBet(msgspec.Struct):
    id: int
    analysis: str
    created_at: datetime.datetime
    price: float | None
    game_time: datetime.datetime
    game_tag: str


class V2NbaDailyBetsBackup(msgspec.Struct):
    id: int | None
    analysis: str | None
    created_at: datetime.datetime | None
    price: float | None
    game_time: datetime.datetime | None
    game_tag: str | None


class V2NflDailyBet(msgspec.Struct):
    id: int
    analysis: str
    created_at: datetime.datetime
    price: float | None
    game_time: datetime.datetime
    game_tag: str


class V2NflDailyBetsBackup(msgspec.Struct):
    id: int | None
    analysis: str | None
    created_at: datetime.datetime | None
    price: float | None
    game_time: datetime.datetime | None
    game_tag: str | None


class V2WnbaDailyBet(msgspec.Struct):
    id: int
    analysis: str
    created_at: datetime.datetime
    price: float | None
    game_time: datetime.datetime
    game_tag: str


class V3NflGame(msgspec.Struct):
    id: int
    home_id: int
    away_id: int
    date: datetime.date


class V3NflGameStat(msgspec.Struct):
    id: int
    game_id: int
    player_id: int
    tfl: decimal.Decimal
    def_td: decimal.Decimal
    sacks: decimal.Decimal
    qb_hits: decimal.Decimal
    fumbles: decimal.Decimal
    fumbles_lost: decimal.Decimal
    solo_tackles: decimal.Decimal
    total_tackles: decimal.Decimal
    forced_fumbles: decimal.Decimal
    pass_deflections: decimal.Decimal
    fumbles_recovered: decimal.Decimal
    defensive_interceptions: decimal.Decimal
    int: decimal.Decimal
    qbr: decimal.Decimal
    rtg: decimal.Decimal
    pass_td: decimal.Decimal
    sacked: str | None
    pass_avg: decimal.Decimal
    pass_yds: decimal.Decimal
    pass_attempts: decimal.Decimal
    pass_completions: decimal.Decimal
    rush_td: decimal.Decimal
    carries: decimal.Decimal
    rush_avg: decimal.Decimal
    rush_yds: decimal.Decimal
    long_rush: decimal.Decimal
    rec_td: decimal.Decimal
    rec_avg: decimal.Decimal
    rec_yds: decimal.Decimal
    long_rec: decimal.Decimal
    targets: decimal.Decimal
    receptions: decimal.Decimal
    kick_returns: decimal.Decimal
    kick_return_td: decimal.Decimal
    kick_return_avg: decimal.Decimal
    kick_return_yds: decimal.Decimal
    kick_return_long: decimal.Decimal
    kick_fg: decimal.Decimal
    kick_points: decimal.Decimal
    kick_extra_points: decimal.Decimal


class V3NflPlayer(msgspec.Struct):
    id: int
    team_id: int
    name: str
    height: str
    position: str
    injuries: str | None
    player_pic: str | None
    role: str
    draft_band: str | None
    is_rookie: bool
    half_ppr_rank: int | None


class V3NflTeam(msgspec.Struct):
    id: int
    name: str
    team_code: str
    wins: int
    losses: int
    ties: int
    points_for: int
    points_against: int
    total_tackles: int
    fumbles_lost: int
    defensive_touchdowns: int
    fumbles_recovered: int
    solo_tackles: int
    defensive_interceptions: int
    qb_hits: int
    tackles_for_loss: int
    pass_deflections: int
    sacks: int
    fumbles: int
    passing_td_allowed: int
    passing_yards_allowed: int
    rushing_yards_allowed: int
    rushing_td_allowed: int | None
    new_notes: str
    team_logo: str | None
    offense_notes: str
    schedule_2025: str | None


class V3NflTeams2024Stat(msgspec.Struct):
    id: int
    name: str
    team_code: str
    wins: int
    losses: int
    ties: int
    points_for: int
    points_against: int
    total_tackles: int
    fumbles_lost: int
    defensive_touchdowns: int
    fumbles_recovered: int
    solo_tackles: int
    defensive_interceptions: int
    qb_hits: int
    tackles_for_loss: int
    pass_deflections: int
    sacks: int
    fumbles: int
    passing_td_allowed: int
    passing_yards_allowed: int
    rushing_yards_allowed: int
    rushing_td_allowed: int | None
    pass_attempts: int | None
    rush_attempts: int | None
    games: int | None
    pass_att_pg: decimal.Decimal | None
    rush_att_pg: decimal.Decimal | None
    pass_yards: int | None
    rush_yards: int | None
    pass_tds: int | None
    rush_tds: int | None


class WnbaPlayer(msgspec.Struct):
    id: int
    name: str
    position: str
    team_id: int
    player_pic: str | None
    player_id: int
    injury: str | None


class WnbaPlayerGameStat(msgspec.Struct):
    id: int
    player_id: int
    game_id: str
    team_id: int
    minutes_played: decimal.Decimal
    points: int
    rebounds: int
    assists: int
    steals: int
    blocks: int
    turnovers: int
    offensive_rebounds: int
    defensive_rebounds: int
    free_throw_percentage: decimal.Decimal
    plus_minus: decimal.Decimal
    technical_fouls: int
    field_goal_attempts: int
    three_point_fg_percentage: decimal.Decimal
    field_goals_made: int
    field_goal_percentage: decimal.Decimal
    three_point_fg_made: int
    free_throw_attempts: int
    three_point_fg_attempts: int
    personal_fouls: int
    free_throws_made: int
    fantasy_points: decimal.Decimal
    home_away: str
    opponent: str
    game_date: datetime.date
    team_abv: str


class WnbaPlayerSeasonStat(msgspec.Struct):
    id: int
    player_id: int
    season_id: int
    games_played: int
    points_per_game: decimal.Decimal
    rebounds_per_game: decimal.Decimal
    assists_per_game: decimal.Decimal
    steals_per_game: decimal.Decimal
    blocks_per_game: decimal.Decimal
    turnovers_per_game: decimal.Decimal
    field_goal_percentage: decimal.Decimal
    three_point_percentage: decimal.Decimal
    free_throw_percentage: decimal.Decimal
    minutes_per_game: decimal.Decimal
    offensive_rebounds_per_game: decimal.Decimal
    defensive_rebounds_per_game: decimal.Decimal
    field_goals_made_per_game: decimal.Decimal
    field_goals_attempted_per_game: decimal.Decimal
    three_pointers_made_per_game: decimal.Decimal
    three_pointers_attempted_per_game: decimal.Decimal
    free_throws_made_per_game: decimal.Decimal
    free_throws_attempted_per_game: decimal.Decimal


class WnbaSeason(msgspec.Struct):
    id: int
    season_year: str


class WnbaTeam(msgspec.Struct):
    id: int
    name: str
    team_city: str
    team_abv: str
    conference: str
    ppg: float
    oppg: float
    wins: int
    loss: int
    team_bpg: float
    team_spg: float
    team_apg: float
    team_fga: float
    team_fgm: float
    team_fta: float
    team_tov: float
