# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.4
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "NflCopyAnalysisParams",
    "NflPlayersWithTeamRow",
    "NflRecentAnalysisKeysRow",
    "QueryResults",
    "nfl_analysis_exists",
    "nfl_copy_analysis",
    "nfl_dedupe_recent_analysis",
    "nfl_players_with_team",
    "nfl_recent_analysis_keys",
    "nfl_teams",
    "nfl_upsert_analysis",
)

import datetime
import decimal
import msgspec
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | decimal.Decimal | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from daily_bets.db import models


class NflCopyAnalysisParams(msgspec.Struct):
    analysis: str
    price: float | None
    game_time: datetime.datetime
    game_tag: str


class NflPlayersWithTeamRow(msgspec.Struct):
    id: int
    team_id: int
    name: str
    height: str
    position: str
    injury: str | None
    player_pic: str | None
    role: str
    draft_band: str | None
    is_rookie: bool
    half_ppr_rank: int | None
    team_abv: str


class NflRecentAnalysisKeysRow(msgspec.Struct):
    game_time: datetime.datetime
    game_tag: str
    player_id: int
    stat: typing.Any | None
    line: decimal.Decimal


NFL_ANALYSIS_EXISTS: typing.Final[str] = """-- name: NflAnalysisExists :one
SELECT EXISTS (
    SELECT 1
    FROM public.v2_nfl_daily_bets
    WHERE
        game_time = $1
        AND game_tag = $2
        AND (analysis->'input'->>'player_id')::int = $3
        AND analysis->'input'->>'stat' = $4
        AND (analysis->'input'->>'line')::numeric = $5::numeric
)
"""

NFL_COPY_ANALYSIS: typing.Final[str] = """-- name: NflCopyAnalysis :copyfrom
INSERT INTO v2_nfl_daily_bets (analysis, price, game_time, game_tag) VALUES ($1, $2, $3, $4)
"""

NFL_DEDUPE_RECENT_ANALYSIS: typing.Final[str] = """-- name: NflDedupeRecentAnalysis :execrows
WITH ranked AS (
    SELECT
        id,
        row_number() OVER (
            PARTITION BY
                game_time,
                game_tag,
                (analysis->'input'->>'player_id')::int,
                analysis->'input'->>'stat',
                (analysis->'input'->>'line')::numeric
            ORDER BY created_at DESC, id DESC
        ) AS rn
    FROM public.v2_nfl_daily_bets
    WHERE created_at >= now() - make_interval(days => $1)
)
DELETE FROM public.v2_nfl_daily_bets b
USING ranked r
WHERE b.id = r.id AND r.rn > 1
"""

NFL_PLAYERS_WITH_TEAM: typing.Final[str] = """-- name: NflPlayersWithTeam :many
SELECT p.id, p.team_id, p.name, p.height, p.position, p.injuries, p.player_pic, p.role, p.draft_band, p.is_rookie, p.half_ppr_rank, T.team_code as team_abv FROM v3_nfl_players P
INNER JOIN v3_nfl_teams T ON P.team_id = T.id
"""

NFL_RECENT_ANALYSIS_KEYS: typing.Final[str] = """-- name: NflRecentAnalysisKeys :many
SELECT
    game_time,
    game_tag,
    (analysis->'input'->>'player_id')::int AS player_id,
    analysis->'input'->>'stat' AS stat,
    (analysis->'input'->>'line')::numeric AS line
FROM public.v2_nfl_daily_bets
WHERE created_at >= now() - make_interval(days => $1)
"""

NFL_TEAMS: typing.Final[str] = """-- name: NflTeams :many
SELECT id, name, team_code, wins, losses, ties, points_for, points_against, total_tackles, fumbles_lost, defensive_touchdowns, fumbles_recovered, solo_tackles, defensive_interceptions, qb_hits, tackles_for_loss, pass_deflections, sacks, fumbles, passing_td_allowed, passing_yards_allowed, rushing_yards_allowed, rushing_td_allowed, "new notes", team_logo, offense_notes, schedule_2025 FROM v3_nfl_teams
"""

NFL_UPSERT_ANALYSIS: typing.Final[str] = """-- name: NflUpsertAnalysis :one
WITH inserted AS (
    INSERT INTO public.v2_nfl_daily_bets (analysis, price, game_time, game_tag)
    SELECT $1, $2, $3, $4
    WHERE NOT EXISTS (
        SELECT 1
        FROM public.v2_nfl_daily_bets
        WHERE
            game_time = $3
            AND game_tag = $4
            AND (analysis->'input'->>'player_id')::int =
                ($1::json->'input'->>'player_id')::int
            AND analysis->'input'->>'stat' = ($1::json->'input'->>'stat')
            AND (analysis->'input'->>'line')::numeric =
                ($1::json->'input'->>'line')::numeric
    )
    RETURNING 1
)
SELECT count(*) FROM inserted
"""


T = typing.TypeVar("T")


class QueryResults(typing.Generic[T]):
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]
        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def nfl_analysis_exists(conn: ConnectionLike, *, game_time: datetime.datetime, game_tag: str, analysis: str, analysis: str, dollar_5: decimal.Decimal) -> bool | None:
    row = await conn.fetchrow(NFL_ANALYSIS_EXISTS, game_time, game_tag, analysis, analysis, dollar_5)
    if row is None:
        return None
    return row[0]


async def nfl_copy_analysis(conn: ConnectionLike, *, params: collections.abc.Sequence[NflCopyAnalysisParams]) -> int:
    records = [
        (param.analysis, param.price, param.game_time, param.game_tag)
        for param in params
    ]
    r = await conn.copy_records_to_table("v2_nfl_daily_bets", columns=["analysis", "price", "game_time", "game_tag"], records=records)
    return int(n) if (p := r.split()) and (n := p[-1]).isdigit() else 0


async def nfl_dedupe_recent_analysis(conn: ConnectionLike, *, days: int) -> int:
    r = await conn.execute(NFL_DEDUPE_RECENT_ANALYSIS, days)
    return int(n) if (p := r.split()) and (n := p[-1]).isdigit() else 0


def nfl_players_with_team(conn: ConnectionLike) -> QueryResults[NflPlayersWithTeamRow]:
    def _decode_hook(row: asyncpg.Record) -> NflPlayersWithTeamRow:
        return NflPlayersWithTeamRow(id=row[0], team_id=row[1], name=row[2], height=row[3], position=row[4], injury=row[5], player_pic=row[6], role=row[7], draft_band=row[8], is_rookie=row[9], half_ppr_rank=row[10], team_abv=row[11])
    return QueryResults[NflPlayersWithTeamRow](conn, NFL_PLAYERS_WITH_TEAM, _decode_hook)


def nfl_recent_analysis_keys(conn: ConnectionLike, *, days: int) -> QueryResults[NflRecentAnalysisKeysRow]:
    def _decode_hook(row: asyncpg.Record) -> NflRecentAnalysisKeysRow:
        return NflRecentAnalysisKeysRow(game_time=row[0], game_tag=row[1], player_id=row[2], stat=row[3], line=row[4])
    return QueryResults[NflRecentAnalysisKeysRow](conn, NFL_RECENT_ANALYSIS_KEYS, _decode_hook, days)


def nfl_teams(conn: ConnectionLike) -> QueryResults[models.V3NflTeam]:
    def _decode_hook(row: asyncpg.Record) -> models.V3NflTeam:
        return models.V3NflTeam(id=row[0], name=row[1], team_code=row[2], wins=row[3], losses=row[4], ties=row[5], points_for=row[6], points_against=row[7], total_tackles=row[8], fumbles_lost=row[9], defensive_touchdowns=row[10], fumbles_recovered=row[11], solo_tackles=row[12], defensive_interceptions=row[13], qb_hits=row[14], tackles_for_loss=row[15], pass_deflections=row[16], sacks=row[17], fumbles=row[18], passing_td_allowed=row[19], passing_yards_allowed=row[20], rushing_yards_allowed=row[21], rushing_td_allowed=row[22], new notes=row[23], team_logo=row[24], offense_notes=row[25], schedule_2025=row[26])
    return QueryResults[models.V3NflTeam](conn, NFL_TEAMS, _decode_hook)


async def nfl_upsert_analysis(conn: ConnectionLike, *, analysis: str, price: float | None, game_time: datetime.datetime, game_tag: str) -> int | None:
    row = await conn.fetchrow(NFL_UPSERT_ANALYSIS, analysis, price, game_time, game_tag)
    if row is None:
        return None
    return row[0]
