# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.4.4
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "QueryResults",
    "WnbaCopyAnalysisParams",
    "WnbaPlayersWithTeamRow",
    "WnbaRecentAnalysisKeysRow",
    "wnba_analysis_exists",
    "wnba_copy_analysis",
    "wnba_dedupe_recent_analysis",
    "wnba_players_with_team",
    "wnba_recent_analysis_keys",
    "wnba_teams",
    "wnba_upsert_analysis",
)

import datetime
import decimal
import msgspec
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    QueryResultsArgsType: typing.TypeAlias = int | float | str | memoryview | decimal.Decimal | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | None

    ConnectionLike: typing.TypeAlias = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from daily_bets.db import models


class WnbaCopyAnalysisParams(msgspec.Struct):
    analysis: str
    price: float | None
    game_time: datetime.datetime
    game_tag: str


class WnbaPlayersWithTeamRow(msgspec.Struct):
    id: int
    name: str
    position: str
    team_id: int
    player_pic: str | None
    player_id: int
    injury: str | None
    team_abv: str


class WnbaRecentAnalysisKeysRow(msgspec.Struct):
    game_time: datetime.datetime
    game_tag: str
    player_id: int
    stat: typing.Any | None
    line: decimal.Decimal


WNBA_ANALYSIS_EXISTS: typing.Final[str] = """-- name: WnbaAnalysisExists :one
SELECT EXISTS (
    SELECT 1
    FROM public.v2_wnba_daily_bets
    WHERE
        game_time = $1
        AND game_tag = $2
        AND (analysis->'input'->>'player_id')::int = $3
        AND analysis->'input'->>'stat' = $4
        AND (analysis->'input'->>'line')::numeric = $5::numeric
)
"""

WNBA_COPY_ANALYSIS: typing.Final[str] = """-- name: WnbaCopyAnalysis :copyfrom
INSERT INTO v2_wnba_daily_bets (analysis, price, game_time, game_tag) VALUES ($1, $2, $3, $4)
"""

WNBA_DEDUPE_RECENT_ANALYSIS: typing.Final[str] = """-- name: WnbaDedupeRecentAnalysis :execrows
WITH ranked AS (
    SELECT
        id,
        row_number() OVER (
            PARTITION BY
                game_time,
                game_tag,
                (analysis->'input'->>'player_id')::int,
                analysis->'input'->>'stat',
                (analysis->'input'->>'line')::numeric
            ORDER BY created_at DESC, id DESC
        ) AS rn
    FROM public.v2_wnba_daily_bets
    WHERE created_at >= now() - make_interval(days => $1)
)
DELETE FROM public.v2_wnba_daily_bets b
USING ranked r
WHERE b.id = r.id AND r.rn > 1
"""

WNBA_PLAYERS_WITH_TEAM: typing.Final[str] = """-- name: WnbaPlayersWithTeam :many
SELECT p.id, p.name, p.position, p.team_id, p.player_pic, p.player_id, p.injury, T.team_abv FROM wnba_players P
INNER JOIN wnba_teams T ON P.team_id = T.id
"""

WNBA_RECENT_ANALYSIS_KEYS: typing.Final[str] = """-- name: WnbaRecentAnalysisKeys :many
SELECT
    game_time,
    game_tag,
    (analysis->'input'->>'player_id')::int AS player_id,
    analysis->'input'->>'stat' AS stat,
    (analysis->'input'->>'line')::numeric AS line
FROM public.v2_wnba_daily_bets
WHERE created_at >= now() - make_interval(days => $1)
"""

WNBA_TEAMS: typing.Final[str] = """-- name: WnbaTeams :many
SELECT id, name, team_city, team_abv, conference, ppg, oppg, wins, loss, team_bpg, team_spg, team_apg, team_fga, team_fgm, team_fta, team_tov FROM wnba_teams
"""

WNBA_UPSERT_ANALYSIS: typing.Final[str] = """-- name: WnbaUpsertAnalysis :one
WITH inserted AS (
    INSERT INTO public.v2_wnba_daily_bets (analysis, price, game_time, game_tag)
    SELECT $1, $2, $3, $4
    WHERE NOT EXISTS (
        SELECT 1
        FROM public.v2_wnba_daily_bets
        WHERE
            game_time = $3
            AND game_tag = $4
            AND (analysis->'input'->>'player_id')::int =
                ($1::json->'input'->>'player_id')::int
            AND analysis->'input'->>'stat' = ($1::json->'input'->>'stat')
            AND (analysis->'input'->>'line')::numeric =
                ($1::json->'input'->>'line')::numeric
    )
    RETURNING 1
)
SELECT count(*) FROM inserted
"""


T = typing.TypeVar("T")


class QueryResults(typing.Generic[T]):
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]
        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def wnba_analysis_exists(conn: ConnectionLike, *, game_time: datetime.datetime, game_tag: str, analysis: str, analysis: str, dollar_5: decimal.Decimal) -> bool | None:
    row = await conn.fetchrow(WNBA_ANALYSIS_EXISTS, game_time, game_tag, analysis, analysis, dollar_5)
    if row is None:
        return None
    return row[0]


async def wnba_copy_analysis(conn: ConnectionLike, *, params: collections.abc.Sequence[WnbaCopyAnalysisParams]) -> int:
    records = [
        (param.analysis, param.price, param.game_time, param.game_tag)
        for param in params
    ]
    r = await conn.copy_records_to_table("v2_wnba_daily_bets", columns=["analysis", "price", "game_time", "game_tag"], records=records)
    return int(n) if (p := r.split()) and (n := p[-1]).isdigit() else 0


async def wnba_dedupe_recent_analysis(conn: ConnectionLike, *, days: int) -> int:
    r = await conn.execute(WNBA_DEDUPE_RECENT_ANALYSIS, days)
    return int(n) if (p := r.split()) and (n := p[-1]).isdigit() else 0


def wnba_players_with_team(conn: ConnectionLike) -> QueryResults[WnbaPlayersWithTeamRow]:
    def _decode_hook(row: asyncpg.Record) -> WnbaPlayersWithTeamRow:
        return WnbaPlayersWithTeamRow(id=row[0], name=row[1], position=row[2], team_id=row[3], player_pic=row[4], player_id=row[5], injury=row[6], team_abv=row[7])
    return QueryResults[WnbaPlayersWithTeamRow](conn, WNBA_PLAYERS_WITH_TEAM, _decode_hook)


def wnba_recent_analysis_keys(conn: ConnectionLike, *, days: int) -> QueryResults[WnbaRecentAnalysisKeysRow]:
    def _decode_hook(row: asyncpg.Record) -> WnbaRecentAnalysisKeysRow:
        return WnbaRecentAnalysisKeysRow(game_time=row[0], game_tag=row[1], player_id=row[2], stat=row[3], line=row[4])
    return QueryResults[WnbaRecentAnalysisKeysRow](conn, WNBA_RECENT_ANALYSIS_KEYS, _decode_hook, days)


def wnba_teams(conn: ConnectionLike) -> QueryResults[models.WnbaTeam]:
    def _decode_hook(row: asyncpg.Record) -> models.WnbaTeam:
        return models.WnbaTeam(id=row[0], name=row[1], team_city=row[2], team_abv=row[3], conference=row[4], ppg=row[5], oppg=row[6], wins=row[7], loss=row[8], team_bpg=row[9], team_spg=row[10], team_apg=row[11], team_fga=row[12], team_fgm=row[13], team_fta=row[14], team_tov=row[15])
    return QueryResults[models.WnbaTeam](conn, WNBA_TEAMS, _decode_hook)


async def wnba_upsert_analysis(conn: ConnectionLike, *, analysis: str, price: float | None, game_time: datetime.datetime, game_tag: str) -> int | None:
    row = await conn.fetchrow(WNBA_UPSERT_ANALYSIS, analysis, price, game_time, game_tag)
    if row is None:
        return None
    return row[0]
