name: Daily MLB ES Test

on:
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Run MLB ES test analysis
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MLB_ANALYSIS_API_URL: ${{ secrets.MLB_ANALYSIS_API_URL }}
          NBA_ANALYSIS_API_URL: ${{ secrets.NBA_ANALYSIS_API_URL }}
          NBA_ALT_ANALYSIS_API_URL: ${{ secrets.NBA_ALT_ANALYSIS_API_URL }}
          NFL_ANALYSIS_API_URL: ${{ secrets.NFL_ANALYSIS_API_URL }}
          WNBA_ANALYSIS_API_URL: ${{ secrets.WNBA_ANALYSIS_API_URL }}
          TRANSLATE_ES_URL: https://us-central1-bestbet-d4d6b.cloudfunctions.net/translate_analysis_es_test
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: uv run -m daily_bets mlb_es_test
