name: Daily NBA Betting Analysis

on:
  schedule:
    # Run at 5 AM PST (1 PM UTC)
    - cron: '0 13 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run-nba-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          
      - name: Run NBA analysis
        env:
          API_KEY: ${{ secrets.API_KEY }}
          NBA_ANALYSIS_API_URL: ${{ secrets.NBA_ANALYSIS_API_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: python -m daily_bets 