name: Daily Bets Analysis

on:
  schedule:
    # 5 AM Pacific / 13 UTC
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  run-mlb-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev
      # - name: Install deps
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install asyncpg httpx pydantic python-dotenv
      #     pip install -e .

      - name: Run Analysis
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MLB_ANALYSIS_API_URL: ${{ secrets.MLB_ANALYSIS_API_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: uv run -m daily_bets
