name: Daily MLB Betting Analysis

on:
  schedule:
    # 5 AM Pacific / 13 UTC
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run-mlb-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install asyncpg httpx pydantic python-dotenv

      - name: Sleep randomly to avoid rate limits
        run: sleep $((RANDOM % 20))

      - name: Run MLB analysis
        env:
          API_KEY:               ${{ secrets.API_KEY }}
          MLB_ANALYSIS_API_URL:  ${{ secrets.MLB_ANALYSIS_API_URL }}
          DB_NAME:               ${{ secrets.DB_NAME }}
          DB_USER:               ${{ secrets.DB_USER }}
          DB_PASS:               ${{ secrets.DB_PASS }}
          DB_HOST:               ${{ secrets.DB_HOST }}
        run: python daily_bets/mlb/mlb.py
