name: Delete Old Bets
on:
  schedule:
    # Run at 6 AM PST (2 PM UTC)
    - cron: "0 14 * * *"
  workflow_dispatch: # Allows manual triggering from GitHub UI
jobs:
  run-nba-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Delete Script
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: uv run -m daily_bets.scripts.delete_old_bets
